### ISSUE TITLE
Compiling error. Can you provide hardware details 

### ISSUE THREAD

**Issue by vcchm** [Xinyuan-LilyGO/T-keyboard#2]
Hello !

The device is not working after compiling for ESP32C3 Dev module. Can you provide more information about the board : flash size (4 Mb ? 8 Mb) - under arduino you get an error when startipn the module if the flash size is not exactly correct ? Wiring (i want to program a wakeup function, but for this I need to now what wakeup pin i can use) ? Thanks in advance

**Comment by LilyGO** [comment]
Hello .Flash size 4MB. No extra pins

**Comment by vcchm** [comment]
Thanks ! Could you share the info & wiring of ESP32 on the main page ? Would help lots of users.

**Comment by LilyGO** [comment]
https://github.com/Xinyuan-LilyGO/T-keyboard#pinout
