### ISSUE TITLE
Drivers

### ISSUE THREAD

**Issue by allthemod** [Xinyuan-LilyGO/T-keyboard#5]
what do you mean by this(in step 4 for the arduino ide):
If you do not have a driver installed, you need to install it (Window:ch341ser2.exe, MAC:ch34x_mac_driver_v1.6.zip https://github.com/LilyGO/LILYGO-T-OI/issues/3#issuecomment-907645945)

how to install it?
and can i use it on other versions of esp32?

**Comment by SkUrRiEr** [comment]
The driver being requested here is the driver for the USB-serial chip, which is a CH340K or equivalent chip.
